### ISSUE TITLE
XZ scaffolds are not written to sexlinked_scaff.list and .list file descriptions are swapped in readme

### ISSUE THREAD

**Issue by zjnolen** [popgenDK/SATC#10]
Hello! Thanks for such an efficient tool, it really works great and is easy to use! Solves an issue I've been trying to sort on my data with other tools almost instantly.

I've noticed that there seems to be a small discrepancy between what the output text suggests:
```
List of abnormal sex linked scaffolds written to ./leo_sexlinked_scaff.list 
List of XZ scaffolds written to ./leo_XZ_scaff.list 

All scaffolds in ./leo_XZ_scaff.list are also in ./leo_sexlinked_scaff.list
```
and what I get, as `sexlinked_scaff.list` contains only the abnormally sex linked and not those in `XZ_scaff.list`. This seems it can be remedied to match what the text suggests by changing [this line](https://github.com/popgenDK/SATC/blob/13c9236ed05c3d07e452deb63b839dfd817ce40a/satc.R#L107) to:
```
write(c(xz,abnormalsexlinked), outlist1)
```
As well, it seems the definitions for these files are [swapped in the readme](https://github.com/popgenDK/SATC/blob/13c9236ed05c3d07e452deb63b839dfd817ce40a/README.md?plain=1#L136-L137).

Best,
Zach

**Comment by casia16** [comment]
Thank you for the input, we have now edited the output text suggestion.

**Comment by zjnolen** [comment]
Awesome, thanks!
