### ISSUE TITLE
Major changes in the method?

### ISSUE THREAD

**Issue by NikoLichi** [popgenDK/SATC#9]
Hi there!
First, I want to thank you for this very nice and easy-to-use tool!
I started using SACT the last November 2021 and I saw that there are some changes on the source code after January 2021. I saw that the signals previously found (in November) now there are not present

I am wondering what could be the explanation for the changes. In my opinion, the code from November was better... But, please see a test on the same sample set I have attached. You can see that Chr42 has a better signal than Chr40 (using the code from  Nov), while the code from January only detects Chr40.
[JanCode.pdf](https://github.com/popgenDK/SATC/files/8416983/JanCode.pdf)
[NOVCode.pdf](https://github.com/popgenDK/SATC/files/8416984/NOVCode.pdf)

**Comment by casia16** [comment]
Hi,
It is hard to know from only the plot you have provided, but yes we have changed the code especially to determine X_Z scaffolds a bit more stringent. We added additional thresholds: homoMedian<1.3 & homoMedian>0.7 & heteroMedian<0.7 & heteroMedian>0.3 also the scaffolds must pass ttest based on sex-group that we have inferred.

**Comment by NikoLichi** [comment]
Thanks for your reply and explanation.
I'll have a look into the raw code and see if I can modify these hard threshold to reconstruct the signal obtained before.
Best.
